export const USER_AVATAR =
  "https://occ-0-6247-2164.1.nflxso.net/dnm/api/v6/K6hjPJd6cR6FpVELC5Pd6ovHRSk/AAAABdpkabKqQAxyWzo6QW_ZnPz1IZLqlmNfK-t4L1VIeV1DY00JhLo_LMVFp936keDxj-V5UELAVJrU--iUUY2MaDxQSSO-0qw.png?r=e6e";

export const API_OPTIONS = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization: `Bearer ${process.env.REACT_APP_TMDB_API_KEY}`,
  },
};

export const NOW_PLAYING_RESULTS = [
  {
    adult: false,
    backdrop_path: "/j3Z3XktmWB1VhsS8iXNcrR86PXi.jpg",
    genre_ids: [28, 878, 12, 14],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 3269.222,
    poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 6.711,
    vote_count: 499,
  },
  {
    adult: false,
    backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 2192.27,
    poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 6.7,
    vote_count: 645,
  },
  {
    adult: false,
    backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
    genre_ids: [28, 53],
    id: 359410,
    original_language: "en",
    original_title: "Road House",
    overview:
      "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
    popularity: 1656.695,
    poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    release_date: "2024-03-08",
    title: "Road House",
    video: false,
    vote_average: 7.075,
    vote_count: 1307,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [28, 14],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 1179.859,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.656,
    vote_count: 1012,
  },
  {
    adult: false,
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 1933.355,
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.352,
    vote_count: 2555,
  },
  {
    adult: false,
    backdrop_path: "/wUp0bUXaveR40ikBhDgWwNTijuD.jpg",
    genre_ids: [28, 9648, 53],
    id: 1181548,
    original_language: "en",
    original_title: "Heart of the Hunter",
    overview:
      "A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.",
    popularity: 1187.536,
    poster_path: "/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg",
    release_date: "2024-03-28",
    title: "Heart of the Hunter",
    video: false,
    vote_average: 5.736,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
    genre_ids: [28, 53],
    id: 984324,
    original_language: "fr",
    original_title: "Le salaire de la peur",
    overview:
      "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
    popularity: 1456.417,
    poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
    release_date: "2024-03-28",
    title: "The Wages of Fear",
    video: false,
    vote_average: 5.913,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 1008.85,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.5,
    vote_count: 1110,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 28, 12],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 787.095,
    poster_path: "/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
    release_date: "2024-03-07",
    title: "Damsel",
    video: false,
    vote_average: 7.132,
    vote_count: 1493,
  },
  {
    adult: false,
    backdrop_path: "/TGsfNWkASegCfAn6ED1b08a9O6.jpg",
    genre_ids: [27, 9648, 53],
    id: 1125311,
    original_language: "en",
    original_title: "Imaginary",
    overview:
      "When Jessica moves back into her childhood home with her family, her youngest stepdaughter Alice develops an eerie attachment to a stuffed bear named Chauncey she finds in the basement. Alice starts playing games with Chauncey that begin playful and become increasingly sinister. As Alice’s behavior becomes more and more concerning, Jessica intervenes only to realize Chauncey is much more than the stuffed toy bear she believed him to be.",
    popularity: 1021.698,
    poster_path: "/9u6HEtZJdZDjPGGJq6YEuhPnoan.jpg",
    release_date: "2024-03-06",
    title: "Imaginary",
    video: false,
    vote_average: 6.088,
    vote_count: 165,
  },
  {
    adult: false,
    backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "en",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 645.573,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.339,
    vote_count: 344,
  },
  {
    adult: false,
    backdrop_path: "/mIBG74mhGEJnBubhYLkCtvplcNr.jpg",
    genre_ids: [27],
    id: 437342,
    original_language: "en",
    original_title: "The First Omen",
    overview:
      "When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.",
    popularity: 609.544,
    poster_path: "/cIzk6GhxEZuweekGFXWEoAyuaMX.jpg",
    release_date: "2024-04-03",
    title: "The First Omen",
    video: false,
    vote_average: 7.026,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 742.651,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.79,
    vote_count: 11144,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 484.124,
    poster_path: "/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 7.112,
    vote_count: 492,
  },
  {
    adult: false,
    backdrop_path: "/qSc5JzPvSm6KxVv54nrn7SNXFtk.jpg",
    genre_ids: [16, 10402, 35],
    id: 1192209,
    original_language: "pt",
    original_title: "Arca de Noé",
    overview:
      "A pair of mice attempt to board Noah's Ark: Vini, a charismatic poet with terrible stage fright, and Tito, a talented and charming guitarist. When the rains come, only one male and one female of each species is allowed on Noah's Ark. With the help of an ingenious cockroach and fate's good luck, Vini and Tito sneak their way onto the Ark and together avert a showdown among the ships carnivores and plant eaters. All the while, the animals perform a series of classic songs inspired by world renowned poet, Vinicius de Moraes. Can these talented stowaways use music to break the tension and help these cooped up creatures survive the 40 days and 40 nights together?",
    popularity: 406.686,
    poster_path: "/j1Rjw6a62UwrbTNT0I3JzZnnCmr.jpg",
    release_date: "2024-01-05",
    title: "Noah's Ark",
    video: false,
    vote_average: 6.984,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 494.584,
    poster_path: "/siduVKgOnABO4WH4lOwPQwaGwJp.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.154,
    vote_count: 804,
  },
  {
    adult: false,
    backdrop_path: "/3Kzc6V4MWs3RXCmE5DhAYnfWL8F.jpg",
    genre_ids: [16, 35, 878],
    id: 1239251,
    original_language: "en",
    original_title: "Megamind vs. the Doom Syndicate",
    overview:
      "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
    popularity: 442.466,
    poster_path: "/fko8CPrnspewLXgFUlUkivyvpHX.jpg",
    release_date: "2024-03-29",
    title: "Megamind vs. the Doom Syndicate",
    video: false,
    vote_average: 5.697,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/8ohejkcQkNgkJgLn71Ws6Kd35g0.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 441.991,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.112,
    vote_count: 7572,
  },
  {
    adult: false,
    backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
    genre_ids: [16, 10751, 14, 12],
    id: 1022796,
    original_language: "en",
    original_title: "Wish",
    overview:
      "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
    popularity: 387.915,
    poster_path: "/vgJZSqKMXWDDx09iSIStGKfHMku.jpg",
    release_date: "2023-11-13",
    title: "Wish",
    video: false,
    vote_average: 6.554,
    vote_count: 1002,
  },
  {
    adult: false,
    backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 404.071,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.809,
    vote_count: 3002,
  },
];

export const POPULAR_RESULTS = [
  {
    adult: false,
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    genre_ids: [878, 12],
    id: 693134,
    original_language: "en",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    popularity: 4742.163,
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    release_date: "2024-02-27",
    title: "Dune: Part Two",
    video: false,
    vote_average: 8.311,
    vote_count: 2746,
  },
  {
    adult: false,
    backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
    genre_ids: [16, 28, 10751, 35, 14],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 3561.356,
    poster_path: "/1THOJsxIj3fqfYewAgIYZp7BfjG.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 7.116,
    vote_count: 948,
  },
  {
    adult: false,
    backdrop_path: "/j3Z3XktmWB1VhsS8iXNcrR86PXi.jpg",
    genre_ids: [28, 878, 12, 14],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 2684.448,
    poster_path: "/tMefBSflR6PGQLv7WvFPpKLZkyk.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 6.726,
    vote_count: 589,
  },
  {
    adult: false,
    backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
    genre_ids: [878, 28, 14, 12],
    id: 601796,
    original_language: "ko",
    original_title: "외계+인 1부",
    overview:
      "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
    popularity: 2013.605,
    poster_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
    release_date: "2022-07-20",
    title: "Alienoid",
    video: false,
    vote_average: 7.087,
    vote_count: 259,
  },
  {
    adult: false,
    backdrop_path: "/qekky2LbtT1wtbD5MDgQvjfZQ24.jpg",
    genre_ids: [28, 53],
    id: 984324,
    original_language: "fr",
    original_title: "Le salaire de la peur",
    overview:
      "When an explosion at an oil well threatens hundreds of lives, a crack team is called upon to make a deadly desert crossing with nitroglycerine in tow.",
    popularity: 1323.176,
    poster_path: "/jFK2ZLQUzo9pea0jfMCHDfvWsx7.jpg",
    release_date: "2024-03-28",
    title: "The Wages of Fear",
    video: false,
    vote_average: 5.932,
    vote_count: 148,
  },
  {
    adult: false,
    backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
    genre_ids: [28, 53],
    id: 359410,
    original_language: "en",
    original_title: "Road House",
    overview:
      "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
    popularity: 1337.993,
    poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    release_date: "2024-03-08",
    title: "Road House",
    video: false,
    vote_average: 7.061,
    vote_count: 1392,
  },
  {
    adult: false,
    backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    genre_ids: [28, 14],
    id: 634492,
    original_language: "en",
    original_title: "Madame Web",
    overview:
      "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    popularity: 1058.25,
    poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    release_date: "2024-02-14",
    title: "Madame Web",
    video: false,
    vote_average: 5.664,
    vote_count: 1054,
  },
  {
    adult: false,
    backdrop_path: "/9c0lHTXRqDBxeOToVzRu0GArSne.jpg",
    genre_ids: [878, 28],
    id: 935271,
    original_language: "en",
    original_title: "After the Pandemic",
    overview:
      "Set in a post-apocalyptic world where a global airborne pandemic has wiped out 90% of the Earth's population and only the young and immune have endured as scavengers. For Ellie and Quinn, the daily challenges to stay alive are compounded when they become hunted by the merciless Stalkers.",
    popularity: 1073.056,
    poster_path: "/p1LbrdJ53dGfEhRopG71akfzOVu.jpg",
    release_date: "2022-03-01",
    title: "After the Pandemic",
    video: false,
    vote_average: 5,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: "/e3gVl1gnxEFKLTF6pn6KRqUPi9K.jpg",
    genre_ids: [10749, 18],
    id: 1127166,
    original_language: "it",
    original_title: "Fabbricante di lacrime",
    overview:
      "Adopted together after a tough childhood in an orphanage, Nica and Rigel realize that unexpected but irresistible feelings pull them together.",
    popularity: 909.15,
    poster_path: "/uoBHsxSgfc3PQsSn98RfnbePHOy.jpg",
    release_date: "2024-04-03",
    title: "The Tearsmith",
    video: false,
    vote_average: 6.773,
    vote_count: 295,
  },
  {
    adult: false,
    backdrop_path: "/wUp0bUXaveR40ikBhDgWwNTijuD.jpg",
    genre_ids: [28, 9648, 53],
    id: 1181548,
    original_language: "en",
    original_title: "Heart of the Hunter",
    overview:
      "A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.",
    popularity: 955.883,
    poster_path: "/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg",
    release_date: "2024-03-28",
    title: "Heart of the Hunter",
    video: false,
    vote_average: 5.9,
    vote_count: 59,
  },
  {
    adult: false,
    backdrop_path: "/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg",
    genre_ids: [28, 14, 10752],
    id: 856289,
    original_language: "zh",
    original_title: "封神第一部：朝歌风云",
    overview:
      "Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.",
    popularity: 922.203,
    poster_path: "/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg",
    release_date: "2023-07-20",
    title: "Creation of the Gods I: Kingdom of Storms",
    video: false,
    vote_average: 6.878,
    vote_count: 192,
  },
  {
    adult: false,
    backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 958.09,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.531,
    vote_count: 1148,
  },
  {
    adult: false,
    backdrop_path: "/2c2Osibm2Q1eEJCW8jc98GQhGdc.jpg",
    genre_ids: [12, 28],
    id: 893334,
    original_language: "en",
    original_title: "The Adventures of Maid Marian",
    overview:
      "Everyone knows the stories of Robin Hood and Maid Marian, but this the story of what happens next. Out of the shadows, a legend returns to save her people from the tyranny of the disgraced Sheriff of Nottingham. Robin Hood remains at war and Marian must put her own combat skills to the test, creating a new tale that will be heralded throughout the ages.",
    popularity: 799.262,
    poster_path: "/oPXzCV01ysDmnmpJOkiVqaZQ5QR.jpg",
    release_date: "2022-05-09",
    title: "The Adventures of Maid Marian",
    video: false,
    vote_average: 5.4,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/b4xaqpUZFUkgyJ1VcFEPXmDML34.jpg",
    genre_ids: [27, 53],
    id: 845783,
    original_language: "en",
    original_title: "Baghead",
    overview:
      "Following the death of her estranged father, Iris learns she has inherited a run-down, centuries-old pub. She travels to Berlin to identify her father’s body and meet with The Solicitor to discuss the estate. Little does she know, when the deed is signed she will become inextricably tied to an unspeakable entity that resides in the pub’s basement – Baghead – a shape-shifting creature that can transform into the dead.",
    popularity: 925.758,
    poster_path: "/lbOyeiiRYAE6Nm2e7xiNAAaRwZB.jpg",
    release_date: "2023-12-28",
    title: "Baghead",
    video: false,
    vote_average: 6.722,
    vote_count: 79,
  },
  {
    adult: false,
    backdrop_path: "/TGsfNWkASegCfAn6ED1b08a9O6.jpg",
    genre_ids: [27, 9648, 53],
    id: 1125311,
    original_language: "en",
    original_title: "Imaginary",
    overview:
      "When Jessica moves back into her childhood home with her family, her youngest stepdaughter Alice develops an eerie attachment to a stuffed bear named Chauncey she finds in the basement. Alice starts playing games with Chauncey that begin playful and become increasingly sinister. As Alice’s behavior becomes more and more concerning, Jessica intervenes only to realize Chauncey is much more than the stuffed toy bear she believed him to be.",
    popularity: 713.644,
    poster_path: "/9u6HEtZJdZDjPGGJq6YEuhPnoan.jpg",
    release_date: "2024-03-06",
    title: "Imaginary",
    video: false,
    vote_average: 6.355,
    vote_count: 197,
  },
  {
    adult: false,
    backdrop_path: "/iqqMJwvPlovftBfdHVrpP2B1IxE.jpg",
    genre_ids: [28, 80, 53, 18],
    id: 551115,
    original_language: "nl",
    original_title: "Penoza: The Final Chapter",
    overview:
      "The Black Widow is not dead ... Drug Queen Carmen van Walraven is hiding in Canada and leads an anonymous life there. One evening a colleague is harassed and Carmen helps her. In self-defense, she kills the perpetrator, is arrested and extradited to the Netherlands. While her children are in shock that their mother is still alive, there are also some people who still have to settle something with Carmen. Everyone is again dragged into an emotional rollercoaster. Carmen will now have deal with her past to save her family.",
    popularity: 662.7,
    poster_path: "/aqRXm3OXSVWuGp3bl8YO4szmos3.jpg",
    release_date: "2019-11-28",
    title: "Penoza: The Final Chapter",
    video: false,
    vote_average: 7.1,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/rKmp0vm6PNaFA0g1bzM70eyWJ6I.jpg",
    genre_ids: [28],
    id: 873972,
    original_language: "en",
    original_title: "Hunters",
    overview:
      "As John T. Wrecker continues his task of protecting a group of refugees from a virus, the threat of something new and even more dangerous grows ever closer in the form of monstrous mutants.",
    popularity: 637.363,
    poster_path: "/3UKlVa1CBeQkRksHV5OfFTO52qd.jpg",
    release_date: "2021-09-13",
    title: "Hunters",
    video: false,
    vote_average: 6.5,
    vote_count: 15,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 28, 12],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 580.647,
    poster_path: "/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
    release_date: "2024-03-07",
    title: "Damsel",
    video: false,
    vote_average: 7.152,
    vote_count: 1558,
  },
  {
    adult: false,
    backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "en",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 650.688,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.342,
    vote_count: 365,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 539.476,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.8,
    vote_count: 11201,
  },
];

export const TOP_RATED_RESULTS = [
  {
    adult: false,
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 127.485,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.704,
    vote_count: 25982,
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 122.233,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.695,
    vote_count: 19699,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 92.071,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.577,
    vote_count: 11900,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 76.389,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.567,
    vote_count: 15298,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 54.601,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.5,
    vote_count: 8182,
  },
  {
    adult: false,
    backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 114.656,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.539,
    vote_count: 15789,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 35.216,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.5,
    vote_count: 4365,
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 103.316,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.515,
    vote_count: 31761,
  },
  {
    adult: false,
    backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 90.273,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.51,
    vote_count: 17404,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 92.042,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.506,
    vote_count: 16713,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 92.034,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.5,
    vote_count: 10896,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 131.143,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.489,
    vote_count: 26933,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    popularity: 111.217,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.479,
    vote_count: 23262,
  },
  {
    adult: false,
    backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 102.799,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.475,
    vote_count: 26456,
  },
  {
    adult: false,
    backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 84.217,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.468,
    vote_count: 8200,
  },
  {
    adult: false,
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 80.921,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.466,
    vote_count: 12309,
  },
  {
    adult: false,
    backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.6,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.464,
    vote_count: 5201,
  },
  {
    adult: false,
    backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 38.161,
    poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.5,
    vote_count: 3462,
  },
  {
    adult: false,
    backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 36.638,
    poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.453,
    vote_count: 4173,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 48.933,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.452,
    vote_count: 12672,
  },
];

export const VIDEO_TRAILER = [
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Official Trailer 3",
    key: "hWbfohXIdEU",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: true,
    published_at: "2023-11-14T13:28:48.000Z",
    id: "6555150253866e00ff06b009",
  },
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Official Trailer 2",
    key: "UkHxhPGpRuA",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: true,
    published_at: "2023-10-14T23:27:40.000Z",
    id: "652b3fbc0cb33516f5c97de1",
  },
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Official Trailer",
    key: "cQfo0HJhCnE",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: true,
    published_at: "2023-07-18T15:00:21.000Z",
    id: "64b6b54f78570e00c6d60c53",
  },
];

export const IMG_CDN_URL = "https://image.tmdb.org/t/p/w500";
